site_name: "Première NSI Lycée du Parc"
site_url: https://parc-nsi.github.io/premiere/
repo_url: https://github.com/parc-nsi/premiere
edit_uri: tree/main/docs/
site_description: "Site  de  première  NSI  du    Lycée  du  Parc  à Lyon " 


#use_directory_urls: true
#voir https://www.mkdocs.org/user-guide/configuration/#docs_dir

nav:
  - Progression: index.md
  - Langages :
    - Chapitre 1 constructions de base d'un langage de programmation : chapitre1.md  
    - Chapitre 5 fonctions, spécification et mise au point, portée d'une variable : chapitre5.md  
  - Types de bases :
    - Chapitre 8 représentation des entiers : chapitre8.md
    - Chapitre 12 codage des caractères : chapitre12.md
    - Chapitre 15 les flottants : chapitre16.md
  - Types construits :
    - Chapitre 6  tableaux à 1 dimension : 
      - Index : chapitre6.md
      - Cours : chapitre6/Cours/tableaux-cours-git.md
    - Chapitre 7 tableaux à 2 dimensions :
      - Index : chapitre7.md
    - Chapitre 15 p-uplets : 
      - Index : chapitre15.md
      - Cours : chapitre15/Cours/puplets-cours-git.md
    - Chapitre 18 dictionnaires : 
      - Index : chapitre18.md
      - Cours : chapitre18/Cours/dictionnaires-cours-git.md      
    - Chapitre 19 traitement de données en tables : 
      - Index: chapitre19.md
      - Cours: chapitre19/Cours/cours-tables-indexation-git.md
      - TP Fusion : chapitre19/TP-Fusion/tp-fusion-git.md
      - TP Recherche et tri : chapitre19/TP-Recherche-Tri/tp-recherche-tri-git.md
  - IHM:
    - Chapitre 3: chapitre3.md
    - Chapitre 4: chapitre4.md
  - Architecture  :
    - Chapitre 9 système d'exploitation et ligne de commandes  : 
      - Index : chapitre9.md
      - Cours : chapitre9/cours-systeme/systeme-cours-git.md
      - Memento Shell : chapitre9/memento-shell/memento-shell-git.md
      - TP1 : chapitre9/TP1/NSI-TP1-systeme-2020-git.md
      - TP2 : chapitre9/TP2/NSI-TP2-systeme-git.md
    - Chapitre 13 portes logiques et circuits combinatoires :
      - Index: chapitre13.md
      - Cours : chapitre13/cours-circuits-logiques-git2.md
    - Chapitre 17 architecture de Von Neumann : chapitre17.md
  - Réseau / Web :
    - Chapitre 2 HTML/CSS : chapitre2.md
    - Chapitre 21  HTTP et formulaires : 
      - Index : chapitre21.md
      - Cours : chapitre21/http-git.md
      - Correction : chapitre21/correction-git.md
    - Chapitre non traité  Interactions côté serveur, PHP et Flask : chapitre230.md
    - Chapitre 23  Interactions dans le navigateur, Javascript : 
      - Index : chapitre23.md
      - Cours : chapitre23/javascript-git2.md
    - Chapitre 25 Réseau TCP/IP:
      - Index : chapitre25.md
      - Cours : chapitre25/reseau-cours-git.md
  - Algorithmique:
    - Chapitre 10  recherches séquentielle et dichotomique : chapitre10.md
    - Chapitre 11  algorithmes de tri : chapitre11.md
    - Chapitre 14  complexité : chapitre14.md
    - Chapitre 20  correction : chapitre20.md
    - Chapitre 22  algorithme KNN : chapitre22.md
    - Chapitre 24  algorithmes gloutons : chapitre24.md
  - Séances : seances.md
  - Automatismes:
    - QCM: divers/qcm.md  
    - Thèmes:
      - Variables:
        - Permutation de variables: automatismes/variables/exo1_variables.md
      - Tests:
        - if / else: automatismes/tests/exo1_tests.md
        - if / elif / .. / else: automatismes/tests/exo2_tests.md
        - Test avec opérateur logique 1: automatismes/tests/exo3_tests.md
        - Test avec opérateur logique 2: automatismes/tests/exo4_tests.md
      - Boucle for :
        - Range épisode 1: automatismes/bouclefor/exo1_range.md
        - Range épisode 2: automatismes/bouclefor/exo2_range.md
        - Range épisode 3: automatismes/bouclefor/exo3_range.md
        - Range épisode 4: automatismes/bouclefor/exo4_range.md
      - Boucle while :
        - Test de boucle avec une comparaison 1: automatismes/bouclewhile/exo1_while.md
        - Test de boucle avec une comparaison 2: automatismes/bouclewhile/exo2_while.md
      - Fonctions:
        - Aire d'un disque: automatismes/fonctions/exo1_fonctions_disque.md
        - Valeur absolue: automatismes/fonctions/exo3_fonctions_valeur_absolue.md
        - Conversion en secondes : automatismes/fonctions/exo2_fonctions_secondes.md
        - Somme des entiers successifs: automatismes/fonctions/exo4_fonctions_somme_for.md
        - Produit des entiers successifs: automatismes/fonctions/exo5_fonctions_produit_for.md
      - Tableaux:
        - Somme d'un tableau: automatismes/tableaux/exo1_tableaux_somme.md
        - Somme d'un tableau, Vincent Bouillot: automatismes/tableaux/exo1_tableaux_somme_bouillot.md
      - Tris:
        - Tri par sélection: automatismes/tris/exo1_tris.md      
    - Automatismes 2020/2021: automatismes/automatismes-2020-2021.md
  - Projets : projets.md
  - Divers:
    - Ressources : divers/ressources.md
    - Outils : divers/outils.md
    - Capytale: divers/capytale.md   
    - Bac:
      - EDS 2021:
        - Amérique du Nord : 
          - Sujet: divers/bac/2021/BACNSI2021AmNo.pdf
          - Fichier élève: divers/bac/2021/amerique_du_nord_2021_eleve.py
          - Éléments de correction: divers/bac/2021/NSI_Amerique_du_Nord_2021.ipynb
        - Candidats libres:
          - Sujet: divers/bac/2021/Metropole_Specialite_NSI_Candidats_libres.pdf
          - Fichier élève: divers/bac/2021/Metropole_Specialite_NSI_Candidats_libres_Eleves.ipynb
          - Éléments de correction: divers/bac/2021/Metropole_Specialite_NSI_Candidats_libres.ipynb    
    - Maths:      
      - Énigmes: divers/maths/enigmes.md
      - Graphes: divers/notebooks/Graphes.ipynb
      - Résidus quadratiques : divers/notebooks/Residu_Quadratique.ipynb
#  - Sandbox : sandbox.md
    
    
    



theme:
  name: material
  palette:                        # Palettes de couleurs jour/nuit
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
          icon: material/weather-night
          name: Passer au mode jour
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
          icon: material/weather-sunny
          name: Passer au mode nuit
  custom_dir: overrides
  font: false
  language: fr
  logo: assets/logo-parc.png
  favicon: assets/logo-parc.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide
    - navigation.tabs.sticky
    - navigation.sections


markdown_extensions:
  - meta
  - abbr
  - def_list     # Les listes de définition.
  - attr_list    # Un peu de CSS et des attributs HTML.
  - admonition   # Blocs colorés  !!! info "ma remarque"
  - pymdownx.details  #   qui peuvent se plier/déplier.  
  - footnotes    # Notes[^1] de bas de page.  [^1]: ma note.
  - pymdownx.caret  # Passage ^^souligné^^ ou en ^exposant^.
  - pymdownx.mark  # Passage ==surligné==.
  - pymdownx.tilde   # Passage ~~barré~~ ou en ~indice~.
  - pymdownx.snippets   # Inclusion de fichiers externe.
  - pymdownx.highlight:  # Coloration syntaxique du code
      #linenums: true
  - pymdownx.tasklist:  # Cases à cocher  - [ ]  et - [x]
      custom_checkbox:    false   #   avec cases d'origine
      clickable_checkbox: true    #   et cliquables.
  - pymdownx.inlinehilite # pour  `#!python  <python en ligne>`
  - pymdownx.superfences: # Imbrication de blocs.
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format        
  - pymdownx.keys   # Touches du clavier.  ++ctrl+d++
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:   # Émojis  :boom:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: false
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - mkdocs_graphviz  #https://gitlab.com/rodrigo.schwencke/mkdocs-graphviz


plugins:
  - search
  - kroki
  - macros:
      verbose: True
      include_dir: include # voir https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#changing-the-directory-of-the-includes
 # - mermaid2
  - mkdocs-jupyter:
      kernel_name: python3
      execute: False
 #     include_source: True

  

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:admin@frederic-junier.org
      name: Mail

    - icon: fontawesome/brands/github
      link: https://github.com/parc-nsi/premiere
      name: Dépôt git


    - icon: mattermost/mattermost
      link: https://fjunier.fr/login
      name: ProfJunierMost

    - icon: fontawesome/solid/university
      link: https://lyceeduparc.fr/ldp/
      name: Lycée du Parc

    

  raw_url: https://parc-nsi.github.io/premiere/-/raw/master/docs/
  io_url: https://parc-nsi.github.io/premiere/
  



copyright:  Sous licence CC BY-NC-SA 4.0

extra_javascript:
  - javascripts/config.js
  #- javascripts/pyodid.js
  - javascripts/interpreter.js
  #- javascripts/repl.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  #- https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.js    #chargé dans l'extension du template html overrides/main.html

extra_css:
  - stylesheets/extra.css
  - xtra/stylesheets/pyoditeur.css
   
 