name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: ts-graphviz/setup-graphviz@v1
      - run: pip install --upgrade pip
      - run: pip install mkdocs-material
      - run: pip install mkdocs-macros-plugin
      - run: pip install graphviz
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip install mkdocs-jupyter
      - run: pip install mkdocs-graphviz
      - run: pip install mkdocs-kroki-plugin
      - run: mkdocs gh-deploy --force
      

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
